niwa_agro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="Give your title",
        default_version='v1',
        description="service",
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)


urlpatterns = [
    
    
    path("", include("users.urls.urls")),

    path("common/", include("app_common.urls.urls")),
    path("course/", include("course.urls.urls")),
    path("certificate/", include("certificate.urls.urls")),
    path('summernote/', include('django_summernote.urls')),

   



    path(
        "swagger/download/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path(
        "swagger/redoc/",
        schema_view.with_ui("redoc", cache_timeout=0),
        name="schema-redoc",
    ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls/urls.py
from django.urls import path
from users import views
from django.conf import settings
from django.conf.urls.static import static
from users.user_views import user_views,admin_views,authentication_views
from app_common.app_common_views import app_common_views
from django.contrib.auth import views as auth_view
from users.user_views.admin_views import course_selection_view
from users.user_views import admin_views
app_name = 'users'


urlpatterns = [
    #Authentication urls
    path('', app_common_views.HomeView.as_view(), name='home'),
    path('admin/', admin_views.AdminDashboard.as_view(), name='admin_dashboard'),
    path('signup', authentication_views.Registration.as_view(), name = "signup"),
    path('login', authentication_views.Login.as_view(), name = "login"),
    path('forgot_password/', authentication_views.ForgotPasswordView.as_view(), name = "forgot_password"),
    path('users/reset_password/<str:token>/', authentication_views.ResetPasswordView.as_view(), name='reset_password'),
    path('logout/', authentication_views.Logout.as_view(), name = "logout"),
    path('account-deletion/', authentication_views.AccountDeletionView.as_view(), name='account_deletion'),


    #user
    path('profile',user_views.ProfileView.as_view(),name="profile"),
    path('profile/update/', user_views.UpdateProfileView.as_view(), name='update_profile'),
    # path('account-details',user_views.AccountDetails.as_view(),name='account_details'),
    path('profile/alladdress',user_views.AllAddress.as_view(),name="alladdress"),
    path('profile/addaddress',user_views.ProfileAddAddress.as_view(),name="profile_addaddress"),
    path('profile/update-address/<str:address_id>/', user_views.ProfileUpdateAddress.as_view(), name='profile_update_address'),
    path('profile/delete-address/<str:address_id>/', user_views.ProfileDeleteAddress.as_view(), name='profile_delete_address'),
    path('support/', user_views.SupportView.as_view(), name='support'),
    path('my-courses/', user_views.MyCoursesView.as_view(), name='my_courses'),
    path('admission-form/<int:course_id>/', user_views.AdmissionFormView.as_view(), name='admission_form'),



    # admin 
    path('students/', admin_views.StudentListView.as_view(), name='student_list'),
    path('add-new-student/', admin_views.AddNewStudentView.as_view(), name='add_new_student'),
    path('student/update/<int:pk>/', admin_views.StudentUpdateView.as_view(), name='update_student'),
    path('get_course_details/<int:course_id>/', admin_views.CourseDetailsView.as_view(), name='get_course_details'),
    path('student-payments/', admin_views.StudentPaymentListView.as_view(), name='student_payment_list'),
    path('export-students/', admin_views.ExportStudentsView.as_view(), name='export_students'),
    path('delete-student/<int:pk>/', admin_views.StudentDeleteView.as_view(), name='delete_student'),
    path('payments/export/', admin_views.ExportPaymentsView.as_view(), name='export_payments'),
    path('payments/add/<int:student_id>/', admin_views.AddNewPaymentView.as_view(), name='add_new_payment'),
    path('students/delete/<int:student_id>/', admin_views.DeleteStudentView.as_view(), name='student_delete'),
    path('student/edit/<int:pk>/', admin_views.StudentpaymentEdit.as_view(), name='student_payment_edit'),
    path('take-attendance/', admin_views.TakeAttendanceView.as_view(), name='take_attendance'),
    path('attendance-report/', admin_views.AttendanceReportView.as_view(), name='attendance_report'),
    path('student-attendance-report/', admin_views.StudentAttendanceReportView.as_view(), name='student_attendance_report'),
    path('batch-details/<int:batch_id>/', admin_views.BatchDetailsView.as_view(), name='batch-details'),
    path('user/user_detail/<int:user_id>', admin_views.StudentDetailView.as_view(), name='user_detail'),
    path('online_class_filter/', admin_views.FilterClass.as_view(), name='online_class_filter'),
    path('batches/', admin_views.BatchListView.as_view(), name='list_batches'),
    path('batches/add', admin_views.AddNewBatchView.as_view(), name='add_new_batch'),
    path('batches/<int:pk>/edit/', admin_views.BatchUpdateView.as_view(), name='edit_batch'),
    path('batches/<int:pk>/delete/', admin_views.BatchDeleteView.as_view(), name='delete_batch'),
    path('student-fees/', admin_views.StudentFeesListView.as_view(), name='student_fees_list'),
    path('get-course-fee/', admin_views.get_course_fee, name='get_course_fee'),
    path('select-course/', admin_views.course_selection_view, name='select_course'),
    path('get-course-fees/<int:course_id>/', admin_views.GetCourseFeesView.as_view(), name='get-course-fees'),
    path('all-users/', admin_views.AllUserListView.as_view(), name='all_user_list'),
    path('user/edit/<int:pk>/', admin_views.UserEditView.as_view(), name='user_edit'),
    path('delete_user/<int:user_id>/', admin_views.DeleteUserView.as_view(), name='delete_user'),
    path('student-details/<int:pk>/', admin_views.StudentsDetailView.as_view(), name='student_details'),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from datetime import datetime, timedelta
from decimal import Decimal
import random
import string
import bleach
from django.db import models
from django.contrib.auth.models import AbstractBaseUser ,PermissionsMixin
from django.urls import reverse
# from course.models import Course
from users.manager import MyAccountManager
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from helpers import utils
from django.conf import settings
from helpers.methods import request_deletion, cancel_deletion
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.core.validators import RegexValidator
import uuid


STATE_CHOICES = [
    ('Andhra Pradesh', 'Andhra Pradesh'),
    ('Arunachal Pradesh', 'Arunachal Pradesh'),
    ('Assam', 'Assam'),
    ('Bihar', 'Bihar'),
    ('Chhattisgarh', 'Chhattisgarh'),
    ('Goa', 'Goa'),
    ('Gujarat', 'Gujarat'),
    ('Haryana', 'Haryana'),
    ('Himachal Pradesh', 'Himachal Pradesh'),
    ('Jharkhand', 'Jharkhand'),
    ('Karnataka', 'Karnataka'),
    ('Kerala', 'Kerala'),
    ('Madhya Pradesh', 'Madhya Pradesh'),
    ('Maharashtra', 'Maharashtra'),
    ('Manipur', 'Manipur'),
    ('Meghalaya', 'Meghalaya'),
    ('Mizoram', 'Mizoram'),
    ('Nagaland', 'Nagaland'),
    ('Odisha', 'Odisha'),
    ('Punjab', 'Punjab'),
    ('Rajasthan', 'Rajasthan'),
    ('Sikkim', 'Sikkim'),
    ('Tamil Nadu', 'Tamil Nadu'),
    ('Telangana', 'Telangana'),
    ('Tripura', 'Tripura'),
    ('Uttar Pradesh', 'Uttar Pradesh'),
    ('Uttarakhand', 'Uttarakhand'),
    ('West Bengal', 'West Bengal'),
]
def generate_unique_username():
    while True:
        # Generate a random string of 8 characters (letters and digits)
        username = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
        # Check if the username already exists
        if not User.objects.filter(username=username).exists():
            return username
        
class Batch(models.Model):
    name = models.CharField(max_length=100, blank=True, null=True)
    timing = models.CharField(max_length=50, blank=True, null=True)
    number_of_students = models.PositiveIntegerField(blank=True, null=True) 
    total_seats = models.PositiveIntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.name:
            self.name = self.name.upper()
        super().save(*args, **kwargs)

    def get_remaining_seats(self):
        return self.total_seats - (self.number_of_students or 0)

    def __str__(self):
        return self.name or "Unknown Batch"
    
class AwardCategory(models.Model):
    category_name = models.CharField(max_length=255)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.category_name
    
class Course(models.Model):
    
    STATUS_CHOICES = [
        ('Active', 'Active'),
        ('Inactive', 'Inactive'),
    ]
    course_code = models.CharField(max_length=100, unique=True, blank=True, null=True)
    award = models.ForeignKey(AwardCategory, on_delete=models.CASCADE, null=True, blank=True)
    course_name = models.CharField(max_length=200, blank=True, null=True)
    course_subject = models.JSONField(default=list, blank=True, null=True)
    course_fees = models.DecimalField(max_digits=10, decimal_places=2,blank=True, null=True)
    course_mrp = models.DecimalField(default=0.0 ,max_digits=10, decimal_places=2,blank=True, null=True)
    minimum_fees = models.DecimalField(max_digits=10, decimal_places=2,blank=True, null=True)
    course_duration = models.CharField(max_length=100,blank=True, null=True)
    exam_fees = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    course_video_link_1 = models.URLField(blank=True, null=True)
    course_video_link_2 = models.URLField(blank=True, null=True)
    course_syllabus = models.TextField(blank=True, null=True)
    eligibility = models.TextField(blank=True, null=True)
    course_image = models.ImageField(upload_to='course_images/', blank=True, null=True)
    pdf_files = models.FileField(upload_to='course_materials/', blank=True, null=True)
    display_course_fees_on_website = models.BooleanField(default=False,blank=True, null=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='Active',blank=True, null=True)
    batch = models.ForeignKey('users.Batch', on_delete=models.CASCADE, null=True, blank=True)
    
    def save(self, *args, **kwargs):  
        # Clean HTML from eligibility and course_syllabus fields  
        self.eligibility = bleach.clean(self.eligibility,strip=False)  
        self.course_syllabus = bleach.clean(self.course_syllabus,strip=False)  
        super().save(*args, **kwargs) 

    def __str__(self):
        return self.course_name 

class User(AbstractBaseUser, PermissionsMixin):
    YESNO = (
        ("yes", "yes"),
        ("no", "no"),
    )
    DISCOUNT_CHOICES = [
        ('amount-', 'Amount -'),
        ('percent-', 'Percent -'),
    ]
    student_image = models.ImageField(upload_to='student_photos/', max_length=250, blank=True, null=True)
    student_signature = models.ImageField(upload_to='student_signatures/', max_length=250, blank=True, null=True)
    roll_number = models.CharField(max_length=20, unique=True, null=True, blank=True)
    abbreviation = models.CharField(max_length=10, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.')], blank=True)
    full_name = models.CharField(max_length=50, null=True, blank=True)
    select_one = models.CharField(max_length=10, choices=[('S/O', 'S/O'), ('D/O', 'D/O'), ('W/O', 'W/O')], blank=True)
    father_husband_name = models.CharField(max_length=100, blank=True)
    show_father_husband_on_certificate = models.BooleanField(default=False)
    mother_name = models.CharField(max_length=100, blank=True)
    course_of_interest = models.ForeignKey(Course, on_delete=models.CASCADE, null=True, blank=True)
    email = models.EmailField(null=True, blank=True, unique=True)
    username = models.CharField(max_length=10, unique=True, null=True, blank=True)
    password = models.CharField(max_length=128, null=True, blank=True)
    contact = models.CharField(max_length=10, null=True, blank=True, unique=True)
    alternative_contact = models.CharField(max_length=10, null=True, blank=True, unique=True)
    date_of_birth = models.DateField(default=timezone.now)
    gender = models.CharField(max_length=10, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], blank=True)
    state = models.CharField(max_length=100, choices=STATE_CHOICES, blank=True)
    city = models.CharField(max_length=100, blank=True)
    pincode = models.CharField(max_length=10, blank=True)
    permanent_address = models.TextField(blank=True)
    aadhar_card_number = models.CharField(max_length=12, blank=True)
    caste = models.CharField(
    max_length=50,
    choices=[
        ('General', 'General'),
        ('OBC', 'OBC'),
        ('SC/ST', 'SC/ST'),
        ('Others', 'Others'),
    ],
)
    qualification = models.CharField(max_length=100, blank=True)
    occupation = models.CharField(max_length=100, blank=True)
    batch = models.ForeignKey('Batch', on_delete=models.SET_NULL, null=True, blank=True)
    remaining_seats_for_batch = models.PositiveIntegerField(blank=True, null=True)
    display_admission_form_id_card_fees_recipt = models.CharField(max_length=10, choices=YESNO, default="yes")
    course_fees = models.FloatField(max_length=100, blank=True, null=True)
    admission_date = models.DateField(default=timezone.now)
    discount_rate = models.CharField(max_length=10, choices=DISCOUNT_CHOICES, default='amount-', blank=True)
    discount_amount = models.FloatField(default=0.0, null=True, blank=True)
    total_fees = models.FloatField(default=0.0, null=True, blank=True, editable=False)
    fees_received = models.FloatField(null=True, blank=True)
    balance = models.DecimalField(max_digits=10, decimal_places=2, editable=False)
    remarks = models.TextField(blank=True)

    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_admitted = models.BooleanField(default=False)

    deletion_requested = models.BooleanField(default=False)
    deletion_date = models.DateTimeField(null=True, blank=True)
    token = models.CharField(max_length=100, null=True, blank=True)

    USERNAME_FIELD = "username"
    REQUIRED_FIELDS = ["password"]

    objects = MyAccountManager()

    def save(self, *args, **kwargs):
        if self.course_of_interest:
            self.course_fees = self.course_of_interest.course_fees or 0.0
            self.total_fees = self.course_fees - Decimal(self.discount_amount or 0)
            self.balance = self.total_fees - Decimal(self.fees_received or 0)
        else:
            self.course_fees = 0.0
            self.total_fees = 0.0
            self.balance = 0.0
        super(User, self).save(*args, **kwargs)

    def __str__(self):
        return self.full_name if self.full_name else "Unnamed User"
    
    @property
    def user_type_display(self):
        return "Student" if self.is_admitted else "User"
    def generate_reset_password_token(self):
        self.token = str(uuid.uuid4())
        self.token_expiration = datetime.now() + timedelta(hours=1)  # Token valid for 1 hour
        self.save()
        return self.token

    def reset_password(self, token, new_password):
        if self.token == token and datetime.now() <= self.token_expiration:
            self.set_password(new_password)
            self.token = None  # Clear the token
            self.token_expiration = None  # Clear expiration
            self.save()
            return True
        return False
    
class Payment(models.Model):
    PAYMENT_MODE_CHOICES = [
        ('cash', 'Cash'),
        ('cheque', 'Cheque'),
        ('demand draft', 'Demand Draft'),

users/templates/users/authtemp/account_deletion.html
<!-- your_app/authtemp/account_deletion.html -->
{% extends 'app_common/base.html' %}
{% load static %}
{% block title %}
Account Deletion | reactedu.in
{% endblock title %}
{% block content %}


<section class="container my-lg-5 my-3 deletion_page">
   <div class="container-fluid">
    <nav style="--bs-breadcrumb-divider: url(&#34;data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='8' height='8'%3E%3Cpath d='M2.5 0L1 1.5 3.5 4 1 6.5 2.5 8l4-4-4-4z' fill='%236c757d'/%3E%3C/svg%3E&#34;);" aria-label="breadcrumb" class="mb-lg-4">
        <ol class="breadcrumb m-0">
          <li class="breadcrumb-item"><a href="{% url 'users:home' %}">Home</a></li>
          <li class="breadcrumb-item active" aria-current="page">Account Delete</li>
        </ol>
      </nav>
    <h3>Account Deletion Process</h3>
    <ul class="listDeletion">
        <li>
            <h6>Requesting Account Deletion</h6>
            <ul>
                <p>Users may request the deletion of their Niwa Agro account at any time by:</p>
                <li>Accessing the account settings in the user portal.</li>
                <li>Contacting our customer support at [support@reactedu.in].</li>
            </ul>
        </li>
        <li>
            <h6>Processing the Request</h6>
            <ul>
                <p>Upon receiving an account deletion request, Niwa Agro will:</p>
                <li>Initiate the deletion process within 7 business days. </li>
                <li>Provide confirmation via email once the account has been successfully deleted.</li>
            </ul>
        </li>
        <li>
            <h6>Data Deletion</h6>
            <ul>
                <p>When an account is deleted:</p>
                <li>All personal data associated with the account will be permanently erased from our systems, including personal details, transaction history, and usage data, unless required by law to retain certain information. </li>
                <li>Users will no longer have access to any previously stored data, and any active subscriptions or services will be terminated.</li>
            </ul>
        </li>
        <li>
            <h6>Retention of Certain Information</h6>
            <ul>
                <p>In compliance with legal, regulatory, or security obligations, Niwa Agro may retain certain information even after account deletion. This may include:</p>
                <li>Records necessary for tax, auditing, or legal reporting purposes.</li>
                <li>Information required for resolving disputes, preventing fraud, or enforcing our policies.</li>
            </ul>
        </li>
        <li>
            <h6>Reactivation</h6>
            <ul>
                <p>Once an account is deleted, it cannot be reactivated. Users wishing to return to Niwa Agro will need to create a new account.</p>
            </ul>
        </li>
        <li>
            <h6>Third-Party Services</h6>
            <ul>
                <p>If you have linked third-party services (e.g., social media, payment platforms) to your Niwa Agro account, please note that deleting your Niwa Agro account will not affect data retained by those third parties. You must contact them directly to manage or delete your information.</p>
            </ul>
        </li>
    </ul>
    {% if user.deletion_requested %}
    <p class="fw-medium fs-6">Your account will be deleted in {{ days_remaining }} days.</p>
    <button onclick="sendDeletionRequest('cancel_deletion')" class="vd_button" id="cancel-deletion">Cancel Deletion</button>
{% else %}
    <button onclick="sendDeletionRequest('request_deletion')" class="vd_button r-deletion">Request Account Deletion</button>
{% endif %}
</div>
</section>

    <script>
        function sendDeletionRequest(action) {
            fetch('', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}',
                },
                body: JSON.stringify({ action: action })
            })
            .then(response => response.json())
            .then(data => {
                alert(data.message);
                if (data.success) {
                    window.location.reload();
                }
            });
        }
    </script>
{% endblock content %}

users/templates/users/authtemp/forgot_password.html
{% extends 'users/authtemp/master.html' %}
{% load static %}
{% block content %}
<div class="container" >
    <h1>Forgot Password</h1>
    <p>Please enter your email address to receive a password reset link.</p>

    <!-- Display form -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Submit</button>
    </form>

    <!-- Display messages -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <a href="{% url 'users:login' %}">Back to Login</a>
</div>
{% endblock content %}

users/templates/users/authtemp/login.html
{% extends 'users/authtemp/master.html' %}
{% load static %}
{% block title %}Login Page{% endblock title %}
{% block content %}
<section class="login_background">
  <div class="login_card">
    <div class="card">
      <div class="row">
        <div class="col-lg-6 col-md-6 col-sm-12 leftside_image">
          <img src="{% static 'image/RATIONAL EDUCATION AND COMPUTER TRAINING_114776258_logo.jpg' %}" alt="Login Image">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12 px-lg-3 border">
          <form method="post" action="">
            {% csrf_token %}
            <h5 class="text-center mt-lg-3 mb-lg-4 fs-1 fw-bold">Welcome!</h5>
            <div class="d-flex justify-content-center">
              <!-- <p class="snippets_alert"> {% include 'snippets/alert.html' %}</p> -->

            </div>
            {% for field in form %}
              <div class="mb-4">
                <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}:</label>
                {{ field }}
              </div>
            {% endfor %}
            <div class="mt-lg-2 d-flex justify-content-end fs-6">
              <button type="button" class="border-0 bg-transparent mt-lg-0 mt-md-0 mt-2" data-bs-toggle="modal" data-bs-target="#forgotPasswordModal">
                <u>Forgot Password?</u>
              </button>
            </div>
            <button class="Login_Button" type="submit">Log in</button>
            <div class="d-flex justify-content-between">
              <div class="text-center w-100 sign_up">
                <small>Don't have an account?</small>
                <a href="{% url 'users:signup' %}" class="ms-lg-1 text-warning text-decoration-none">Sign up</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>

<!-- Password Reset Modal -->
<div class="modal fade" id="forgotPasswordModal" tabindex="-1" aria-labelledby="forgotPasswordModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="forgotPasswordModalLabel">Forgot Password !</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>Provide the email address associated with your account to recover your password.</p>
        <form method="post" action="{% url 'users:forgot_password' %}"> 
          {% csrf_token %}
      
          <div class="form-group">
              <label for="id_email" class="mb-2">Email Address</label>
              {{ form2.email }}
          </div>
          
          <div class="d-flex justify-content-center lh-lg my-3">
              <button type="submit" class="Login_Button p-1 ">Submit</button>
          </div>
      </form>
      
    </div>
    </div>
  </div>
</div>
</section>
<script>
  document.querySelectorAll('.toggle-password').forEach(function(toggleIcon) {
     toggleIcon.addEventListener('click', function() {
         var passwordField = this.closest('.form-group').querySelector('input[name="password"]');
         var type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
         passwordField.setAttribute('type', type);
         this.classList.toggle('fa-eye-slash');
     });
 });
 </script>
{% endblock content %}

users/templates/users/authtemp/logout_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Logout Confirmation</title>
    <link rel="stylesheet" href="">
</head>
<body>
    <div class="container">
        <h1>Logout Confirmation</h1>
        <p>Are you sure you want to logout?</p>
        <div class="buttons">
            <a href="?confirm=true" class="btn btn-primary">Yes, Logout</a>
            <a href="?cancel=true" class="btn btn-secondary">Cancel</a>
        </div>
    </div>
</body>
</html>

users/templates/users/authtemp/registration.html
{% extends 'users/authtemp/master.html' %}
{% load static %}
{% block title %}Signup Page{% endblock title %}

{% block content %}
<section class=" login_background">
    <div class="signup_card">
      <div class="card " >
        <div class="row">
          <div class="col col-lg-6 px-lg-3">
            <div class="card-body border p-2 ">
                <h5 class="text-center fs-3 fw-bold"> Create an Account !</h5>         
                {% if messages %}
                        <!-- <div class="alert-container">
                            {% for message in messages %}
                                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                    {{ message }}
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endfor %}
                        </div> -->
                    {% endif %}
                    <form method="post">
                        {% csrf_token %}
                        {% if request.GET.next %}
                            <input type="hidden" name="next" value="{{ request.GET.next }}">
                        {% endif %}
                        {% for field in form %}
                            <div class="form-group">
                                <label for="{{ field.id_for_label }}" class="col-form-label">{{ field.label }}:</label>
                                {{ field }}
                                {% if field.name == 'password'  %}
                                    <i class="fa-solid fa-eye " id="toggle-password"></i>
                                {% endif %}
                                {% if field.name == 'confirm_password' %}
                                    <i class="fa-solid fa-eye " id="toggle-confirm-password"></i>
                                {% endif %}
                            </div>
                        {% endfor %}
                        {% if form.errors %}
                            <div class="form-errors">
                                <ul>
                                    {% for field in form %}
                                        {% for error in field.errors %}
                                            <li>{{ error }}</li>
                                        {% endfor %}
                                    {% endfor %}
                                    {% for error in form.non_field_errors %}
                                        <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                            </div>
                        {% endif %}
                        <button type="submit" class="Login_Button">Register</button>
                    </form>
                    
                <div class=" text-center w-100 sign_up">
                    <small>Already have an account?</small>
                    <a href="{% url 'users:login' %}" class="ms-lg-1 text-warning text-decoration-none ">Login</a>
                  </div>
              </div>
              
          </div>
          <div class="col col-lg-6 leftside_image">
            <img src="{% static 'image/RATIONAL EDUCATION AND COMPUTER TRAINING_114776258_logo.jpg' %}" alt="">
        </div>
        </div>
      </div>
    </div>
  </section>


  <script>
    document.getElementById('toggle-password')?.addEventListener('click', function() {
        var passwordField = document.querySelector('input[name="password"]');
        var type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordField.setAttribute('type', type);
        this.classList.toggle('fa-eye-slash');
    });
 
    document.getElementById('toggle-confirm-password')?.addEventListener('click', function() {
        var confirmPasswordField = document.querySelector('input[name="confirm_password"]');
        var type = confirmPasswordField.getAttribute('type') === 'password' ? 'text' : 'password';
        confirmPasswordField.setAttribute('type', type);
        this.classList.toggle('fa-eye-slash');
    });
</script>

{% endblock content %}

users/templates/users/authtemp/reset_password.html
{% extends 'users/authtemp/master.html' %}
{% load static %}
{% block content %}
<div class="container">
    <h1>Reset Password</h1>
    <p>Please enter your new password.</p>

    <!-- Display form -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Reset Password</button>
    </form>

    <!-- Display messages -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    <a href="{% url 'users:login' %}">Back to Login</a>
</div>
{% endblock content %}